AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample Form for bref (HTTP API)

Globals:
  Function:
    Timeout: 10
    MemorySize: 512

Parameters:

  AppName:
    Type: String
    Default: "try-bref-form"
    Description: Application name.

  AppEnv:
    Type: String
    AllowedValues: [dev, stg, prod]
    Description: Application environment (dev, stg or prod)

  AppDebug:
    Type: String
    AllowedValues: ["true", "false"]
    Description: Enable debug mode (true for debug logging, false for production)

  SmtpHost:
    Type: String
    Default: "email-smtp.ap-northeast-1.amazonaws.com"
    Description: SMTP server host name.

  SmtpPort:
    Type: String
    Default: "587"
    Description: SMTP server port.

  EmailFrom:
    Type: String
    Description: SES verified envelope-from email address

  EmailFromName:
    Type: String
    Default: ""
    Description: Display name for EmailFrom.

  EmailAdmin:
    Type: String
    Description: Administrator email address

  MailSubjectAdmin:
    Type: String
    Default: "【お問い合わせ】がありました"
    Description: Email subject for admin notification

  MailSubjectUser:
    Type: String
    Default: "【自動返信】お問い合わせありがとうございます"
    Description: Email subject for user auto-reply

  RecaptchaType:
    Type: String
    AllowedValues: [enterprise, v3, v2-checkbox, v2-invisible]
    Default: v3
    Description: reCAPTCHA type (enterprise, v3, v2-checkbox or v2-invisible)

  RecaptchaProjectId:
    Type: String
    Default: ""
    Description: GCP project ID for reCAPTCHA Enterprise

  RecaptchaScoreThreshold:
    Type: String
    Default: "0.5"
    Description: reCAPTCHA score threshold (0.0 - 1.0)

  LogRetentionInDays:
    Type: Number
    Default: 90
    Description: CloudWatch Logs retention period (days)

  SessionHandler:
    Type: String
    AllowedValues: [file, dynamodb]
    Default: dynamodb
    Description: Session storage handler (file or dynamodb)

Resources:
  TryFormSessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AppName}-${AppEnv}-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expires_at
      Tags:
        - Key: Environment
          Value: !Ref AppEnv

  TryFormHttpApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${AppName}-${AppEnv}
      RetentionInDays: !Ref LogRetentionInDays
      Tags:
        - Key: Environment
          Value: !Ref AppEnv

  TryFormHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      AccessLogSettings:
        DestinationArn: !GetAtt TryFormHttpApiLogGroup.Arn
        Format: '{"requestId":"$context.requestId","host":"$context.domainName","path":"$context.path","httpMethod":"$context.httpMethod","status":"$context.status","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","routeKey":"$context.routeKey","ua":"$context.identity.userAgent","error":"$context.error.message","responseLength":"$context.responseLength"}'
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowOrigins:
          - "*"
      Tags:
        Environment: !Ref AppEnv

  TryFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppName}-${AppEnv}
      CodeUri: src
      Runtime: provided.al2
      Handler: public/index.php
      Layers:
        - arn:aws:lambda:ap-northeast-1:534081306603:layer:php-84-fpm:35
      Tags:
        Environment: !Ref AppEnv
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${AppEnv}/*
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AppName}-${AppEnv}:*
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
              Resource: !GetAtt TryFormSessionTable.Arn
      Environment:
        Variables:
          PHP_INI_SCAN_DIR: /var/task/php-conf:/opt/bref/etc/php/conf.d
          APP_ENV: !Ref AppEnv
          APP_DEBUG: !Ref AppDebug
          SES_SMTP_USER: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/ses-smtp-user:SecretString}}'
          SES_SMTP_PASS: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/ses-smtp-pass:SecretString}}'
          SMTP_HOST: !Ref SmtpHost
          SMTP_PORT: !Ref SmtpPort
          EMAIL_FROM: !Ref EmailFrom
          EMAIL_FROM_NAME: !Ref EmailFromName
          EMAIL_ADMIN: !Ref EmailAdmin
          MAIL_SUBJECT_ADMIN: !Ref MailSubjectAdmin
          MAIL_SUBJECT_USER: !Ref MailSubjectUser
          RECAPTCHA_TYPE: !Ref RecaptchaType
          RECAPTCHA_SITE_KEY: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/recaptocha-site-key:SecretString}}'
          RECAPTCHA_SECRET_KEY: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/recaptocha-secret-key:SecretString}}'
          RECAPTCHA_PROJECT_ID: !Ref RecaptchaProjectId
          RECAPTCHA_SCORE_THRESHOLD: !Ref RecaptchaScoreThreshold
          SESSION_HANDLER: !Ref SessionHandler
          SESSION_DYNAMODB_TABLE: !Sub ${AppName}-${AppEnv}-sessions
      Events:
        RootEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref TryFormHttpApi
            Path: /
            Method: ANY

        ProxyEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref TryFormHttpApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  TryFormHttpApiEndpoint:
    Description: "HTTP API endpoint"
    Value: !Sub "https://${TryFormHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/contact/"
